name: books
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  go_router: ^14.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/image/
  fonts:
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto-Regular.ttf
        - asset: asset/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Regular.ttf
        - asset: asset/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: asset/fonts/Poppins-Black.ttf
          weight: 900
        - asset: asset/fonts/Poppins-Italic.ttf
          style: italic
